language: dart
sudo: required
addons:
  chrome: stable
dart:
  - stable
dart_task:
  # TODO enable once automated tests are working
  # - test: --platform vm
  # - test: --platform chrome
  - dartanalyzer: lib test # TODO fix examples and add example dir
  - dartfmt: true
