name: github
version: 8.1.0
description: A high-level GitHub API Client Library that uses Github's v3 API
homepage: https://github.com/SpinlockLabs/github.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  http: ^0.13.0
  http_parser: ^4.0.0
  json_annotation: ^4.0.0
  meta: ^1.3.0

dev_dependencies:
  build_runner: any
  build_test: any
  build_web_compilers: any
  json_serializable: ^4.0.0
  mockito: ^5.0.0
  pedantic: ^1.10.0
  test: ^1.16.0
  yaml: ^3.0.0
  