name: github
version: 6.2.2
description: A high-level GitHub API Client Library that uses Github's v3 API
homepage: https://github.com/SpinlockLabs/github.dart

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  http: '^0.12.0'
  http_parser: ^3.1.1
  json_annotation: '>=2.0.0 <4.0.0'
  meta: ^1.1.0

dev_dependencies:
  build_runner: any
  build_test: any
  build_web_compilers: any
  json_serializable: ^3.2.2
  mockito: ^3.0.0
  pedantic: ^1.0.0
  test: ^1.3.0
  yaml: ^2.2.0
