name: github
version: 0.1.0
description: GitHub API Client Library
homepage: "https://github.com/DirectMyFile/github.dart"
author: "Kenneth Endfinger <kaendfinger@gmail.com>"
environment:
  sdk: ">=1.5.0"
dependencies:
  jsonx: ">=1.2.5 <2.0.0"
  http: ">=0.11.1+1 <0.12.0"
  quiver: ">=0.18.2 <0.19.0"
dev_dependencies:
  browser: ">=0.10.0+2 <0.11.0"
