name: github
version: 9.25.0
description: A high-level GitHub API Client Library that uses Github's v3 API
homepage: https://github.com/SpinlockLabs/github.dart

environment:
  sdk: ^3.1.0

dependencies:
  http: ^1.0.0
  http_parser: ^4.0.0
  json_annotation: ^4.9.0
  meta: ^1.7.0

dev_dependencies:
  build_runner: ^2.2.1
  build_test: ^2.1.2
  build_web_compilers: '>=3.2.6 < 5.0.0'
  collection: ^1.15.0
  dependency_validator: ^3.0.0
  json_serializable: ^6.6.1
  lints: ^4.0.0
  mockito: ^5.3.2
  nock: ^1.1.3
  pub_semver: ^2.0.0
  test: ^1.21.6
  yaml: ^3.1.0
  yaml_edit: ^2.2.0
