name: github
version: 4.0.0-dev
author: Kenneth Endfinger <kaendfinger@gmail.com>
description: GitHub API Client Library
homepage: https://github.com/DirectMyFile/github.dart
environment:
  sdk: '>=2.0.0-dev.36 <3.0.0'
dependencies:
  html: '>=0.12.0 <0.14.0'
  http: '^0.11.3'
  http_parser: ^3.1.1
  json_annotation: '>=0.2.8 <2.0.0'
  xml: '>=2.0.0 <4.0.0'
dev_dependencies:
  build_runner: ^0.9.0
  json_serializable: ^1.0.0
  test: '^0.12.0'
  mockito: '^1.0.1'
