name: github
version: 0.5.7
author: Kenneth Endfinger <kaendfinger@gmail.com>
description: GitHub API Client Library
homepage: https://github.com/DirectMyFile/github.dart
environment:
  sdk: '>=1.5.0'
dependencies:
  http: '>=0.11.0 <0.11.5'
  quiver: '>=0.18.2 <0.19.0'
dev_dependencies:
  browser: '>=0.10.0+2 <0.11.0'
  scheduled_test: '>=0.11.1 <0.12.0'
  hop: '>=0.31.0+1 <0.32.0'
  yaml: '2.0.0'
