name: github
version: 8.0.0-dev
description: An unoffical Dart Octokit - (Github Client API)
environment:
    sdk: ">=2.6.0 <3.0.0"
dependencies:
    dio: ^3.0.9
    built_value: ^7.1.0
    built_collection: ^4.3.2
dev_dependencies:
    built_value_generator: ^7.1.0
    build_runner: ^1.7.1
    test: ^1.3.0

