name: github
version: 9.5.0
description: A high-level GitHub API Client Library that uses Github's v3 API
homepage: https://github.com/SpinlockLabs/github.dart

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  http: ^0.13.0
  http_parser: ^4.0.0
  json_annotation: ^4.7.0
  meta: ^1.3.0

dev_dependencies:
  build_runner: any
  build_test: any
  build_web_compilers: any
  collection: ^1.15.0
  dependency_validator:
  json_serializable: ^6.0.0
  lints: ^2.0.0
  mockito: ^5.3.0
  pub_semver: 
  test: #^1.16.0
  yaml: ^3.0.0
  yaml_edit: 
