name: github
version: 4.0.0-dev
author: Kenneth Endfinger <kaendfinger@gmail.com>
description: GitHub API Client Library
homepage: https://github.com/DirectMyFile/github.dart
environment:
  sdk: '>=1.21.0 <2.0.0'
dependencies:
  html: '>=0.12.0 <0.14.0'
  http: '^0.11.3'
  json_annotation: '^0.2.0'
  markdown: '^0.11.1'
  quiver: '>=0.20.0 <0.26.0'
  xml: '^2.0.0'
dev_dependencies:
  browser: '^0.10.0+2'
  build_runner: ^0.5.0
  json_serializable: '^0.2.4'
  source_gen: '^0.7.0'
  test: '^0.12.0'
  mockito: '^1.0.1'
