name: github
version: 0.6.1
author: Kenneth Endfinger <kaendfinger@gmail.com>
description: GitHub API Client Library
homepage: https://github.com/DirectMyFile/github.dart
environment:
  sdk: '>=1.5.0'
dependencies:
  quiver: '>=0.18.2 <0.19.0'
dev_dependencies:
  browser: '>=0.10.0+2 <0.11.0'
  hop: '>=0.31.0+1 <0.32.0'
  unittest: '>=0.11.0+3 <0.12.0'
  yaml: 2.0.0
