name: github
version: 2.2.0
author: Kenneth Endfinger <kaendfinger@gmail.com>
description: GitHub API Client Library
homepage: https://github.com/DirectMyFile/github.dart
environment:
  sdk: '>=1.6.0'
dependencies:
  crypto: '>=0.9.0 <1.0.1'
  html5lib: '>=0.12.0 <0.13.0'
  quiver: '>=0.20.0 <0.25.0'
  xml: '>=2.0.0 <3.0.0'
dev_dependencies:
  browser: '>=0.10.0+2 <0.11.0'
  hop: '>=0.31.0+1 <0.32.0'
  junitconfiguration: '>=1.0.0 <2.0.0'
  mock: '>=0.11.0+2 <0.12.0'
  unittest: '>=0.11.0+3 <0.12.0'
  yaml: '>=2.0.0 <2.2.0'
